name: 'autofix.ci'
description: 'Automatically fix formatting/lint issues in pull requests'
branding:
  icon: 'check-circle'
  color: 'green'
runs:
  using: 'node16'
  main: 'index.js'
inputs:
  fail-fast:
    description: 'Cancel all other workflows associated with a commit when fixing it.'
    required: false
    default: 'true'
  commit-message:
    description: 'The commit message to use when fixing a commit.'
    required: false
